# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Btn_Page_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn_Page_2.setFont(font)
        self.Btn_Page_2.setObjectName("Btn_Page_2")
        self.gridLayout.addWidget(self.Btn_Page_2, 1, 2, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Home)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.Home)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Home)
        self.Screen_1 = QtWidgets.QWidget()
        self.Screen_1.setObjectName("Screen_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Screen_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.Screen_1)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Screen_1)
        self.Screen_2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Screen_2.setFont(font)
        self.Screen_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Screen_2.setAutoFillBackground(False)
        self.Screen_2.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.Screen_2.setObjectName("Screen_2")
        self.label_1 = QtWidgets.QLabel(self.Screen_2)
        self.label_1.setGeometry(QtCore.QRect(9, 9, 105, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_1.setFont(font)
        self.label_1.setLineWidth(0)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.Btn_Exit = QtWidgets.QPushButton(self.Screen_2)
        self.Btn_Exit.setGeometry(QtCore.QRect(580, 320, 121, 41))
        self.Btn_Exit.setObjectName("Btn_Exit")
        self.stackedWidget.addWidget(self.Screen_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 3)
        self.Btn_Home = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn_Home.setFont(font)
        self.Btn_Home.setObjectName("Btn_Home")
        self.gridLayout.addWidget(self.Btn_Home, 1, 0, 1, 1)
        self.Btn_Page_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Btn_Page_1.setFont(font)
        self.Btn_Page_1.setObjectName("Btn_Page_1")
        self.gridLayout.addWidget(self.Btn_Page_1, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Page_2.setText(_translate("MainWindow", "Page 2"))
        self.label_3.setText(_translate("MainWindow", "Home"))
        self.label.setText(_translate("MainWindow", "Screen 1"))
        self.label_1.setText(_translate("MainWindow", "Screen 2"))
        self.Btn_Exit.setText(_translate("MainWindow", "Exit"))
        self.Btn_Home.setText(_translate("MainWindow", "Home"))
        self.Btn_Page_1.setText(_translate("MainWindow", "Page 1"))

